name: Deploy GH pages

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
        run: cd docs/website && npm install && npm run build

      - name: Deploy
        cache:
          yarn: true
          script:
            - git config --global user.name "${GH_NAME}"
            - git config --global user.email "${GH_EMAIL}"
            - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
            - cd docs/website && yarn install && GIT_USER="${GH_NAME}" yarn run publish-gh-pages