name: Deploying to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: cd docs/website && npm install && npm run build
      - run: git config --global user.email "${GH_EMAIL}"
      - run: git config --global user.name "${GH_NAME}"
      - run: echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      - run: cd docs/website && GIT_USER=${GH_NAME} && CURRENT_BRANCH=master && npm run publish-gh-pages