name: Deploying to GitHub Pages

on: [push, pull_request]

jobs:
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - checkout
      - run:
          command: |
            git config --global user.email "${GH_EMAIL}"
            git config --global user.name "${GH_NAME}"
            echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
            cd docs/website && npm install && GIT_USER=${GH_NAME} npm run publish-gh-pages