name: Deploy GH pages

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Build
      - run: cd docs/website && npm install && npm run build

      - name: Deploy
      - run: git config --global user.name "${GH_NAME}"
      - run: git config --global user.email "${GH_EMAIL}"
      - run: echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
      - run: cd docs/website && npm install && GIT_USER="${GH_NAME}" npm run publish-gh-pages